import {$,esc} from '../ui/dom.js';
import {t,getLang} from '../config/i18n.js';
import {enumText,recommendationsText} from '../config/labels.js';
import {createConclusion} from '../domain/models.js';
import {toast} from '../ui/feedback.js';
export function createConclusionFeature({store,dialog}){
  const state=()=>store.getState(),getMed=id=>state().medications.find(x=>x.id===id),getEvent=id=>state().events.find(x=>x.id===id);const scopes=['conclusions','report','shell'];
  function render(){const s=state(),list=$('#conclusionList'),empty=$('#conclusionEmpty');empty.hidden=s.assessments.length>0;list.innerHTML=s.assessments.map(a=>{const c=s.conclusions.find(x=>x.drugId===a.drugId&&x.eventId===a.eventId),m=getMed(a.drugId),e=getEvent(a.eventId);return`<article class="record-card"><div class="record-title"><h3>${esc(m?.genericName||'?')} × ${esc(e?.term||'?')}</h3><p>Naranjo: ${a.score??'—'} ${esc(a.classification?enumText('naranjo',a.classification):'')}</p></div><div class="record-detail"><span>Final conclusion</span><b>${esc(c?.conclusion?enumText('conclusion',c.conclusion):'—')}</b><small>${esc(c?.relationshipType?enumText('relationship',c.relationshipType):'')}</small></div><div class="record-detail"><span>Recommendation</span><b>${esc(recommendationsText(c))}</b></div><div class="record-actions"><button class="btn btn-secondary btn-small" data-edit-conclusion="${a.id}">${c?t('edit'):t('add')}</button></div></article>`}).join('')}
  function openEditor(assessmentId){const s=state(),a=s.assessments.find(x=>x.id===assessmentId);if(!a)return;let c=s.conclusions.find(x=>x.drugId===a.drugId&&x.eventId===a.eventId);const isNew=!c;if(!c)c=createConclusion(a.drugId,a.eventId);const recs=['avoid_culprit','avoid_related_class','alternative_allowed','refer_allergy_specialist','further_testing','no_avoidance_required','other'];dialog.open({title:'Final Pharmacist Conclusion',kicker:`${getMed(a.drugId)?.genericName||'?'} × ${getEvent(a.eventId)?.term||'?'}`,html:`<div class="form-grid cols-2"><label>${getLang()==='th'?'ข้อสรุป':'Conclusion'}<select name="conclusion"><option value=""></option>${['confirmed','highly_probable','probable','possible','unlikely','unable_to_assess'].map(x=>`<option value="${x}" ${c.conclusion===x?'selected':''}>${enumText('conclusion',x)}</option>`).join('')}</select></label><label>${getLang()==='th'?'ประเภทความสัมพันธ์':'Relationship type'}<select name="relationship"><option value=""></option>${['allergic','non_allergic_adr','indeterminate'].map(x=>`<option value="${x}" ${c.relationshipType===x?'selected':''}>${enumText('relationship',x)}</option>`).join('')}</select></label><label class="span-2">${getLang()==='th'?'เหตุผลทางคลินิก':'Clinical reasoning'}<textarea name="reasoning" rows="4">${esc(c.reasoning)}</textarea></label><div class="span-2"><label>${getLang()==='th'?'คำแนะนำ':'Recommendations'}</label><div class="check-grid">${recs.map(x=>`<label class="check-row"><input type="checkbox" name="recs" value="${x}" ${c.recommendations.includes(x)?'checked':''}><span>${enumText('recommendation',x)}</span></label>`).join('')}</div></div><label class="span-2">${getLang()==='th'?'คำแนะนำเพิ่มเติม':'Recommendation note'}<textarea name="recNote" rows="2">${esc(c.recommendationNote)}</textarea></label></div>`,onSave:()=>{Object.assign(c,{conclusion:dialog.val('conclusion'),relationshipType:dialog.val('relationship'),reasoning:dialog.val('reasoning').trim(),recommendations:dialog.checked('recs'),recommendationNote:dialog.val('recNote').trim(),updatedAt:new Date().toISOString()});if(!c.conclusion||!c.relationshipType||!c.reasoning)return toast(getLang()==='th'?'กรุณากรอกข้อสรุปและเหตุผล':'Conclusion and reasoning are required');if(isNew)s.conclusions.push(c);store.update(()=>{}, {scopes});dialog.close()}})}
  function init(){$('#conclusionSection').addEventListener('click',e=>{const b=e.target.closest('[data-edit-conclusion]');if(b)openEditor(b.dataset.editConclusion)})}
  return {init,render};
}
