import {$,esc,fmt} from '../ui/dom.js';
import {t,getLang} from '../config/i18n.js';
import {createMedication} from '../domain/models.js';
import {markLinkedAssessmentsNeedsReview,markLinkedClinicalModulesNeedsReview} from '../domain/assessment-state.js';

export function createMedicationFeature({store,dialog}){
  const state=()=>store.getState(),getMed=id=>state().medications.find(x=>x.id===id);
  const scopes=['medications','timeline','naranjo','modules','conclusions','report','shell'];
  function render(){const s=state();$('#medEmpty').hidden=s.medications.length>0;$('#medList').innerHTML=s.medications.map(m=>`<article class="record-card"><div class="record-title"><h3>${esc(m.genericName||'-')}</h3><p>${esc(m.tradeName||'')} ${m.tradeName?'·':''} ${esc(m.dose)} ${esc(m.route)} ${esc(m.frequency)}</p></div><div class="record-detail"><span>Role</span><b class="badge ${m.role}">${m.role==='suspected'?t('suspected'):t('concomitant')}</b></div><div class="record-detail"><span>Exposure</span><b>${fmt(m.startDateTime)} → ${m.stopDateTime?fmt(m.stopDateTime):'—'}</b></div><div class="record-actions"><button class="btn btn-ghost btn-small" data-edit-med="${m.id}">${t('edit')}</button><button class="btn btn-danger-soft btn-small" data-del-med="${m.id}">${t('delete')}</button></div></article>`).join('')}
  function openEditor(id=null){const s=state(),m=id?getMed(id):createMedication();dialog.open({title:id?(getLang()==='th'?'แก้ไขยา':'Edit medication'):(getLang()==='th'?'เพิ่มยา':'Add medication'),kicker:'MEDICATION',html:`<p class="dialog-required-note"><b>*</b> ${getLang()==='th'?'ช่องจำเป็นสำหรับบันทึกรายการยา':'Required to save the medication'}</p><div class="form-grid cols-2"><label><span class="field-required">Generic name</span><input name="generic" aria-required="true" value="${esc(m.genericName)}"></label><label>Trade name<input name="trade" value="${esc(m.tradeName)}"></label><label><span class="field-required">Dose</span><input name="dose" aria-required="true" value="${esc(m.dose)}"></label><label><span class="field-required">Route</span><input name="route" aria-required="true" value="${esc(m.route)}"></label><label><span class="field-required">Frequency</span><input name="frequency" aria-required="true" value="${esc(m.frequency)}"></label><label>Role<select name="role"><option value="suspected" ${m.role==='suspected'?'selected':''}>${t('suspected')}</option><option value="concomitant" ${m.role==='concomitant'?'selected':''}>${t('concomitant')}</option></select></label><label><span class="field-required">Start datetime</span><input type="datetime-local" name="start" aria-required="true" value="${esc(m.startDateTime)}"></label><label>Stop datetime<input type="datetime-local" name="stop" value="${esc(m.stopDateTime)}"></label></div>`,onSave:()=>{const patch={genericName:dialog.val('generic').trim(),tradeName:dialog.val('trade').trim(),dose:dialog.val('dose').trim(),route:dialog.val('route').trim(),frequency:dialog.val('frequency').trim(),role:dialog.val('role'),startDateTime:dialog.val('start'),stopDateTime:dialog.val('stop')};const missing=[];if(!patch.genericName)missing.push('generic');if(!patch.dose)missing.push('dose');if(!patch.route)missing.push('route');if(!patch.frequency)missing.push('frequency');if(!patch.startDateTime)missing.push('start');if(missing.length)return dialog.error(getLang()==='th'?'กรุณากรอกช่องที่มีเครื่องหมาย * ให้ครบก่อนบันทึกรายการยา':'Complete all fields marked * before saving the medication',{fields:missing});if(patch.stopDateTime&&new Date(patch.stopDateTime)<new Date(patch.startDateTime))return dialog.error(getLang()==='th'?'Stop ต้องไม่ก่อน Start':'Stop cannot precede Start',{fields:['stop','start']});const changed=id&&JSON.stringify({...m,updatedAt:null})!==JSON.stringify({...m,...patch,updatedAt:null});Object.assign(m,patch,{updatedAt:new Date().toISOString()});if(!id)s.medications.push(m);else if(changed){markLinkedAssessmentsNeedsReview(s,{drugId:m.id});markLinkedClinicalModulesNeedsReview(s,{drugId:m.id})}store.update(()=>{}, {scopes});dialog.close()}})}
  function remove(id){if(!confirm(getLang()==='th'?'ลบยารายการนี้และ Naranjo/Conclusion ที่เชื่อมโยงหรือไม่?':'Delete this medication and linked assessments/conclusions?'))return;store.update(s=>{s.medications=s.medications.filter(x=>x.id!==id);s.assessments=s.assessments.filter(a=>a.drugId!==id);s.conclusions=s.conclusions.filter(c=>c.drugId!==id);s.clinicalModules=s.clinicalModules.filter(m=>m.drugId!==id);if(!s.assessments.some(a=>a.id===store.getSelectedAssessmentId()))store.setSelectedAssessmentId(null,{notifyScope:false})},{scopes})}
  function init(){$('#addMedBtn').addEventListener('click',()=>openEditor());$('#medSection').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editMed)openEditor(b.dataset.editMed);if(b.dataset.delMed)remove(b.dataset.delMed)})}
  return {init,render};
}
