import {$,esc} from '../ui/dom.js';
import {t,getLang} from '../config/i18n.js';
import {enumText} from '../config/labels.js';
import {createDiagnosis,createAllergy} from '../domain/models.js';
import {toast} from '../ui/feedback.js';

export function createPatientFeature({store,dialog}){
  const scopes=['patient','report','shell'];
  const state=()=>store.getState();
  function render(){const s=state();$('#caseId').value=s.metadata.caseId;$('#caseChip').textContent=s.metadata.caseId;$('#patientHn').value=s.patient.hn;$('#patientAge').value=s.patient.age.value;$('#patientAgeUnit').value=s.patient.age.unit;$('#patientSex').value=s.patient.sex;$('#visitDate').value=s.patient.visitDate;$('#patientNote').value=s.patient.note;$('#diagnosisNote').value=s.patient.diagnosisNote;$('#diagnosisList').innerHTML=s.patient.diagnoses.filter(d=>d.text?.trim()).map(d=>`<div class="mini-row"><div><strong>${esc(d.text)}</strong></div><div class="record-actions"><button class="btn btn-ghost btn-small" data-edit-dx="${d.id}">${t('edit')}</button><button class="btn btn-danger-soft btn-small" data-del-dx="${d.id}">${t('delete')}</button></div></div>`).join('');$('#allergyList').innerHTML=s.patient.allergyHistory.map(a=>`<div class="mini-row"><div><strong>${esc(a.drug||'-')}</strong><small>${esc(a.reaction||'-')} · ${esc(enumText('severity',a.severity)||'-')}</small></div><div class="record-actions"><button class="btn btn-ghost btn-small" data-edit-allergy="${a.id}">${t('edit')}</button><button class="btn btn-danger-soft btn-small" data-del-allergy="${a.id}">${t('delete')}</button></div></div>`).join('');const ok=s.patient.hn.trim()&&s.patient.age.value!==''&&s.patient.sex&&s.patient.visitDate;$('#caseStatus').textContent=ok?t('complete'):t('incomplete');$('#caseStatus').classList.toggle('complete',!!ok)}
  function diagnosisDialog(id=null){const s=state(),item=id?s.patient.diagnoses.find(x=>x.id===id):createDiagnosis();dialog.open({title:'Diagnosis',kicker:'PATIENT',html:`<label>${getLang()==='th'?'Diagnosis / Problem':'Diagnosis / problem'}<input name="text" value="${esc(item.text)}" autofocus></label>`,onSave:()=>{const text=dialog.val('text').trim();if(!text)return;if(id)item.text=text;else{item.text=text;s.patient.diagnoses.push(item)}store.update(()=>{}, {scopes});dialog.close()}})}
  function allergyDialog(id=null){const s=state(),a=id?s.patient.allergyHistory.find(x=>x.id===id):createAllergy();dialog.open({title:getLang()==='th'?'ประวัติแพ้ยา / ADR เดิม':'Previous allergy / ADR',kicker:'ALLERGY HISTORY',html:`<div class="form-grid cols-2"><label>Drug / Drug class<input name="drug" value="${esc(a.drug)}"></label><label>${getLang()==='th'?'อาการ':'Reaction'}<input name="reaction" value="${esc(a.reaction)}"></label><label>${getLang()==='th'?'วันที่โดยประมาณ':'Approximate date'}<input name="date" type="date" value="${esc(a.approxDate)}"></label><label>Severity<select name="severity"><option value=""></option>${['mild','moderate','severe'].map(x=>`<option value="${x}" ${a.severity===x?'selected':''}>${enumText('severity',x)}</option>`).join('')}</select></label><label class="span-2">${getLang()==='th'?'ข้อมูล previous exposure':'Previous exposure'}<input name="exposure" value="${esc(a.previousExposure)}"></label><label class="span-2">Comment<textarea name="comment" rows="2">${esc(a.comment)}</textarea></label></div>`,onSave:()=>{Object.assign(a,{drug:dialog.val('drug').trim(),reaction:dialog.val('reaction').trim(),approxDate:dialog.val('date'),severity:dialog.val('severity'),previousExposure:dialog.val('exposure'),comment:dialog.val('comment')});if(!a.drug||!a.reaction)return toast(getLang()==='th'?'กรุณาระบุยาและอาการ':'Drug and reaction are required');if(!id)s.patient.allergyHistory.push(a);store.update(()=>{}, {scopes});dialog.close()}})}
  function init(){
    const map=[['#patientHn',v=>state().patient.hn=v],['#patientAge',v=>state().patient.age.value=v],['#patientAgeUnit',v=>state().patient.age.unit=v],['#patientSex',v=>state().patient.sex=v],['#visitDate',v=>state().patient.visitDate=v],['#patientNote',v=>state().patient.note=v],['#diagnosisNote',v=>state().patient.diagnosisNote=v]];
    for(const[sel,set]of map)$(sel).addEventListener('input',e=>{set(e.target.value);store.update(()=>{}, {scopes:['report','shell'],touch:true})});
    $('#addDiagnosisBtn').addEventListener('click',()=>diagnosisDialog());$('#addAllergyBtn').addEventListener('click',()=>allergyDialog());
    $('#caseSection').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editDx)diagnosisDialog(b.dataset.editDx);if(b.dataset.delDx)store.update(s=>{s.patient.diagnoses=s.patient.diagnoses.filter(x=>x.id!==b.dataset.delDx)},{scopes});if(b.dataset.editAllergy)allergyDialog(b.dataset.editAllergy);if(b.dataset.delAllergy)store.update(s=>{s.patient.allergyHistory=s.patient.allergyHistory.filter(x=>x.id!==b.dataset.delAllergy)},{scopes})});
  }
  return {init,render};
}
