import {$,esc,fmt} from '../ui/dom.js';
import {t,getLang} from '../config/i18n.js';
import {enumText,phenotypeText,mechanismText,seriousnessText,recommendationsText,moduleName} from '../config/labels.js';
import {NARANJO_QUESTIONS} from '../domain/naranjo.js';
import {validateCase} from '../domain/validation.js';
import {APP_VERSION,SCHEMA_VERSION} from '../domain/models.js';
import {buildSummary} from '../services/summary.js';
import {moduleResultText,moduleInterpretation} from '../services/clinical-presentation.js';
import {copyText} from '../services/files.js';
import {toast} from '../ui/feedback.js';

const errors={
 th:{case_id_required:'ไม่พบ Case ID',patient_hn_required:'กรุณาระบุ HN',patient_age_required:'กรุณาระบุอายุ',patient_age_unit_invalid:'หน่วยอายุไม่ถูกต้อง',patient_sex_required:'กรุณาเลือกเพศ Male/Female',visit_date_required:'กรุณาระบุ Visit date',medication_required:'ต้องมีรายการยาอย่างน้อย 1 รายการ',event_required:'ต้องมี ADR event อย่างน้อย 1 เหตุการณ์',medication_generic_required:'ยาทุกรายการต้องมี generic name',medication_fields_required:'กรุณาระบุ dose, route, frequency และเวลาเริ่มยา',medication_role_invalid:'Role ของยาไม่ถูกต้อง',medication_date_invalid:'วันที่/เวลายาไม่ถูกต้อง หรือ Stop ก่อน Start',event_fields_required:'ADR event ต้องมีอาการ, onset, severity, outcome และ management',event_severity_invalid:'Severity ของ ADR ไม่ถูกต้อง',event_timing_invalid:'Reaction timing ไม่ถูกต้อง',event_date_invalid:'วันที่/เวลา ADR ไม่ถูกต้อง หรือ End ก่อน Onset',assessment_reference_invalid:'Naranjo อ้างอิงยา/เหตุการณ์ที่ไม่มีอยู่',assessment_duplicate_pair:'พบ Naranjo ซ้ำในคู่ Drug × ADR เดียวกัน',assessment_drug_not_suspected:'Naranjo ต้องผูกกับยาที่เป็น Suspected เท่านั้น',assessment_needs_review:'มี Naranjo ที่ต้องทบทวนใหม่',assessment_incomplete:'มี Naranjo ที่ยังไม่ครบ',event_without_assessment:'ทุก ADR event ต้องมี Naranjo อย่างน้อย 1 คู่ก่อน Final Print',assessment_required:'ต้องมี Naranjo assessment อย่างน้อย 1 รายการ',conclusion_required:'ทุก Naranjo ต้องมี Final Pharmacist Conclusion ที่ครบ',allergic_phenotype_required:'กรณีสรุปเป็น Allergic ต้องระบุ Drug Allergy phenotype',allergic_phenotype_detail_required:'เมื่อเลือก Phenotype = อื่น ๆ ต้องระบุรายละเอียด',diagnosis_missing:'ยังไม่ได้ระบุ Diagnosis',clinical_module_needs_review:'มี Optional Clinical Module ที่ควรทบทวนหลังข้อมูลต้นทางเปลี่ยน',clinical_module_incomplete:'มี Optional Clinical Module ที่ข้อมูลไม่ครบ',clinical_module_id_invalid:'Clinical Module ID ไม่ถูกต้องหรือซ้ำ',clinical_module_type_invalid:'พบชนิด Clinical Module ที่ไม่รองรับ',clinical_module_reference_invalid:'Clinical Module อ้างอิงยา/ADR ไม่ถูกต้อง',conclusion_reference_invalid:'Final Conclusion อ้างอิงยา/ADR ไม่ถูกต้อง',conclusion_duplicate_pair:'พบ Final Conclusion ซ้ำในคู่ Drug × ADR เดียวกัน'},
 en:{case_id_required:'Case ID is missing',patient_hn_required:'HN is required',patient_age_required:'Age is required',patient_age_unit_invalid:'Age unit is invalid',patient_sex_required:'Select Male/Female',visit_date_required:'Visit date is required',medication_required:'At least one medication is required',event_required:'At least one ADR event is required',medication_generic_required:'Every medication requires a generic name',medication_fields_required:'Dose, route, frequency and start time are required',medication_role_invalid:'Medication role is invalid',medication_date_invalid:'Medication date/time is invalid or stop precedes start',event_fields_required:'ADR event requires term, onset, severity, outcome and management',event_severity_invalid:'ADR severity is invalid',event_timing_invalid:'Reaction timing is invalid',event_date_invalid:'ADR date/time is invalid or end precedes onset',assessment_reference_invalid:'Assessment has a broken Drug/Event reference',assessment_duplicate_pair:'Duplicate Naranjo Drug × ADR pair',assessment_drug_not_suspected:'Naranjo can only be linked to a Suspected drug',assessment_needs_review:'A Naranjo assessment needs review',assessment_incomplete:'A Naranjo assessment is incomplete',event_without_assessment:'Each ADR event needs at least one Naranjo pair before final print',assessment_required:'At least one Naranjo assessment is required',conclusion_required:'Each Naranjo pair requires a complete pharmacist conclusion',allergic_phenotype_required:'An Allergic conclusion requires a Drug Allergy phenotype',allergic_phenotype_detail_required:'Other phenotype requires a description',diagnosis_missing:'Diagnosis has not been entered',clinical_module_needs_review:'An optional clinical module should be reviewed after source data changed',clinical_module_incomplete:'An optional clinical module has incomplete data',clinical_module_id_invalid:'Clinical Module ID is missing or duplicated',clinical_module_type_invalid:'Unsupported Clinical Module type',clinical_module_reference_invalid:'Clinical Module has an invalid Drug/ADR reference',conclusion_reference_invalid:'Final conclusion has an invalid Drug/ADR reference',conclusion_duplicate_pair:'Duplicate final conclusion for the same Drug × ADR pair'}
};
export function errorText(key,l=getLang()){return errors[l]?.[key]||key}

export function createReportFeature({store}){
  const state=()=>store.getState(),getMed=id=>state().medications.find(x=>x.id===id),getEvent=id=>state().events.find(x=>x.id===id);
  function render(){const s=state(),lang=getLang(),v=validateCase(s,{forPrint:true}),panel=$('#validationPanel');panel.className=`validation-panel ${v.valid?'valid':'invalid'}`;const warningHtml=v.warnings.length?`<div class="validation-warnings"><strong>${t('warnings')}</strong><ul>${v.warnings.map(x=>`<li>${esc(errorText(x))}</li>`).join('')}</ul></div>`:'';panel.innerHTML=v.valid?`<strong>${t('validReady')}</strong>${warningHtml}`:`<strong>${t('printBlocked')}</strong><ul>${v.errors.map(x=>`<li>${esc(errorText(x))}</li>`).join('')}</ul>${warningHtml}`;$('#printBtn').disabled=!v.valid;
    const R=lang==='th'?{ageSex:'อายุ / เพศ',visit:'วันที่ Visit',diagnosis:'Diagnosis',allergy:'ประวัติแพ้ยา / ADR เดิม',drugClass:'ยา / กลุ่มยา',reaction:'อาการ',severity:'Severity',date:'วันที่',previousExposure:'Previous exposure',comment:'หมายเหตุ',meds:'ประวัติการใช้ยา',generic:'Generic',trade:'Trade',regimen:'ขนาด / วิธีใช้',role:'Role',start:'เริ่ม',stop:'หยุด',events:'ADR events',event:'เหตุการณ์',phenotype:'Phenotype',timing:'Timing',mechanism:'กลไกที่สงสัย',seriousness:'Seriousness',onset:'เริ่มอาการ',end:'สิ้นสุด',outcome:'Outcome',overview:'ภาพรวม Naranjo และข้อสรุปเภสัชกร',drug:'ยา',score:'คะแนน',naranjo:'Naranjo',final:'Final Pharmacist Conclusion',question:'คำถาม',answer:'คำตอบ',rationale:'เหตุผล / หลักฐาน',reasoning:'เหตุผลทางคลินิก',recommendation:'คำแนะนำ',modules:'Optional Clinical Modules',module:'Module',result:'ผล',status:'สถานะ',interpretation:'การแปลผล',summary:'Clinical Summary',management:'การจัดการ',evidence:'Objective evidence',clinicalNote:'Clinical note',current:'Current',needsReview:'Needs Review'}:{ageSex:'Age / Sex',visit:'Visit date',diagnosis:'Diagnosis',allergy:'Previous allergy / ADR history',drugClass:'Drug / class',reaction:'Reaction',severity:'Severity',date:'Date',previousExposure:'Previous exposure',comment:'Comment',meds:'Medication exposure',generic:'Generic',trade:'Trade',regimen:'Regimen',role:'Role',start:'Start',stop:'Stop',events:'ADR events',event:'Event',phenotype:'Phenotype',timing:'Timing',mechanism:'Suspected mechanism',seriousness:'Seriousness',onset:'Onset',end:'End',outcome:'Outcome',overview:'Naranjo & Pharmacist conclusion overview',drug:'Drug',score:'Score',naranjo:'Naranjo',final:'Final Pharmacist Conclusion',question:'Question',answer:'Answer',rationale:'Rationale / evidence',reasoning:'Clinical reasoning',recommendation:'Recommendation',modules:'Optional Clinical Modules',module:'Module',result:'Result',status:'Status',interpretation:'Interpretation',summary:'Clinical summary',management:'Management',evidence:'Objective evidence',clinicalNote:'Clinical note',current:'Current',needsReview:'Needs Review'};
    const dx=s.patient.diagnoses.filter(d=>d.text?.trim()).map(d=>d.text).join(', ')||'-';
    const allergyRows=s.patient.allergyHistory.map(a=>`<tr><td>${esc(a.drug)}</td><td>${esc(a.reaction)}</td><td>${esc(enumText('severity',a.severity)||'-')}</td><td>${esc(a.approxDate||'-')}</td><td>${esc(a.previousExposure||'-')}</td><td>${esc(a.comment||'-')}</td></tr>`).join('');
    const meds=s.medications.map(m=>`<tr><td>${esc(m.genericName)}</td><td>${esc(m.tradeName||'-')}</td><td>${esc([m.dose,m.route,m.frequency].filter(Boolean).join(' · '))}</td><td>${esc(m.role==='suspected'?t('suspected'):t('concomitant'))}</td><td>${esc(fmt(m.startDateTime))}</td><td>${esc(m.stopDateTime?fmt(m.stopDateTime):'—')}</td></tr>`).join('');
    const evs=s.events.map(e=>`<tr><td>${esc(e.term)}</td><td>${esc(phenotypeText(e))}<br><small>${esc(mechanismText(e))}</small></td><td>${esc(enumText('timing',e.timing))}</td><td>${esc(enumText('severity',e.severity))}</td><td>${esc(seriousnessText(e))}</td><td>${esc(fmt(e.onsetDateTime))} → ${esc(e.endDateTime?fmt(e.endDateTime):'—')}</td><td>${esc(e.outcome)}</td></tr>`).join('');
    const ass=s.assessments.map(a=>{const m=getMed(a.drugId),e=getEvent(a.eventId),c=s.conclusions.find(x=>x.drugId===a.drugId&&x.eventId===a.eventId);return`<tr><td>${esc(m?.genericName||'?')}</td><td>${esc(e?.term||'?')}</td><td>${a.score??'—'}</td><td>${esc(a.classification?enumText('naranjo',a.classification):'-')}</td><td>${esc(c?.conclusion?enumText('conclusion',c.conclusion):'-')}<br><small>${esc(c?.relationshipType?enumText('relationship',c.relationshipType):'')}</small></td></tr>`}).join('');
    const naranjoDetails=s.assessments.map(a=>{const m=getMed(a.drugId),e=getEvent(a.eventId),c=s.conclusions.find(x=>x.drugId===a.drugId&&x.eventId===a.eventId),rows=NARANJO_QUESTIONS.map(q=>{const item=a.answers?.[q.id]??{},ans=item.answer?t(item.answer):'-';return`<tr><td>${q.id}</td><td>${esc(q[lang])}</td><td>${esc(ans)}</td><td>${item.answer?q.scores[item.answer]:0}</td><td>${esc(item.rationale||'-')}</td></tr>`}).join('');return`<div class="report-block"><h3>${esc(m?.genericName||'?')} × ${esc(e?.term||'?')} — Naranjo ${a.score??'—'} ${esc(a.classification?enumText('naranjo',a.classification):'')}</h3><table class="report-table"><thead><tr><th>#</th><th>${R.question}</th><th>${R.answer}</th><th>${R.score}</th><th>${R.rationale}</th></tr></thead><tbody>${rows}</tbody></table><div class="report-summary"><b>${R.final}:</b> ${esc(c?.conclusion?enumText('conclusion',c.conclusion):'-')} (${esc(c?.relationshipType?enumText('relationship',c.relationshipType):'-')})\n<b>${R.reasoning}:</b> ${esc(c?.reasoning||'-')}\n<b>${R.recommendation}:</b> ${esc(recommendationsText(c))}${c?.recommendationNote?` · ${esc(c.recommendationNote)}`:''}</div></div>`}).join('');
    const eventDetails=s.events.map(e=>`<div class="report-summary"><b>${esc(e.term)}</b>\n${R.management}: ${esc(e.management||'-')}\n${R.evidence}: ${esc(e.objectiveEvidence||'-')}\n${R.clinicalNote}: ${esc(e.clinicalNote||'-')}</div>`).join('<br>');
    const mods=s.clinicalModules.map(m=>`<tr><td>${moduleName(m.type)}</td><td>${esc(getMed(m.drugId)?.genericName||'-')}</td><td>${esc(getEvent(m.eventId)?.term||'-')}</td><td>${esc(moduleResultText(m))}</td><td>${esc(m.status==='needs_review'?R.needsReview:R.current)}</td><td>${esc(m.status==='needs_review'?t('moduleNeedsReview'):moduleInterpretation(m,s.patient))}</td></tr>`).join('');
    const patientNote=s.patient.note?.trim()?`<div class="report-summary">${esc(s.patient.note)}</div>`:'';
    $('#reportSheet').innerHTML=`<div class="report-header"><div><p class="section-kicker">BANGKOK HOSPITAL HAT YAI</p><h2>BHH Drug Allergy Assessment</h2><p>ADR · Drug allergy phenotype · Causality · Pharmacist conclusion</p></div><img class="report-logo" src="assets/bhh-logo.svg" alt="Bangkok Hospital Hat Yai"></div><div class="report-meta"><div class="meta-cell"><span>Case ID</span><strong>${esc(s.metadata.caseId)}</strong></div><div class="meta-cell"><span>HN</span><strong>${esc(s.patient.hn||'-')}</strong></div><div class="meta-cell"><span>${R.ageSex}</span><strong>${esc(s.patient.age.value||'-')} ${esc(enumText('ageUnit',s.patient.age.unit))} · ${esc(enumText('sex',s.patient.sex))}</strong></div><div class="meta-cell"><span>${R.visit}</span><strong>${esc(s.patient.visitDate||'-')}</strong></div></div><div class="report-block"><h3>${R.diagnosis}</h3><div class="report-summary">${esc(dx)}${s.patient.diagnosisNote?`\n${esc(s.patient.diagnosisNote)}`:''}</div>${patientNote}</div><div class="report-block"><h3>${R.allergy}</h3><table class="report-table"><thead><tr><th>${R.drugClass}</th><th>${R.reaction}</th><th>${R.severity}</th><th>${R.date}</th><th>${R.previousExposure}</th><th>${R.comment}</th></tr></thead><tbody>${allergyRows||'<tr><td colspan="6">—</td></tr>'}</tbody></table></div><div class="report-block"><h3>${R.meds}</h3><table class="report-table"><thead><tr><th>${R.generic}</th><th>${R.trade}</th><th>${R.regimen}</th><th>${R.role}</th><th>${R.start}</th><th>${R.stop}</th></tr></thead><tbody>${meds||'<tr><td colspan="6">—</td></tr>'}</tbody></table></div><div class="report-block"><h3>${R.events}</h3><table class="report-table"><thead><tr><th>${R.event}</th><th>${R.phenotype} / ${R.mechanism}</th><th>${R.timing}</th><th>${R.severity}</th><th>${R.seriousness}</th><th>${R.onset} → ${R.end}</th><th>${R.outcome}</th></tr></thead><tbody>${evs||'<tr><td colspan="7">—</td></tr>'}</tbody></table>${eventDetails}</div><div class="report-block"><h3>${R.overview}</h3><table class="report-table"><thead><tr><th>${R.drug}</th><th>ADR</th><th>${R.score}</th><th>${R.naranjo}</th><th>${R.final}</th></tr></thead><tbody>${ass||'<tr><td colspan="5">—</td></tr>'}</tbody></table></div>${naranjoDetails}${mods?`<div class="report-block"><h3>${R.modules}</h3><table class="report-table"><thead><tr><th>${R.module}</th><th>${R.drug}</th><th>ADR</th><th>${R.result}</th><th>${R.status}</th><th>${R.interpretation}</th></tr></thead><tbody>${mods}</tbody></table></div>`:''}<div class="report-block"><h3>${R.summary}</h3><div class="report-summary">${esc(buildSummary(s,lang))}</div></div><div class="report-block report-footer">Generated by BHH Drug Allergy Assessment v${APP_VERSION} · Schema ${SCHEMA_VERSION}. Clinical decision support; final interpretation remains with the treating clinical team.</div>`;
  }
  function init(){$('#printBtn').addEventListener('click',()=>{const v=validateCase(state(),{forPrint:true});if(!v.valid){toast(t('printBlocked'));render();return}window.print()});$('#copyThBtn').addEventListener('click',async()=>{await copyText(buildSummary(state(),'th'));toast(t('copySuccess'))});$('#copyEnBtn').addEventListener('click',async()=>{await copyText(buildSummary(state(),'en'));toast(t('copySuccess'))})}
  return {init,render};
}
