import test from 'node:test';
import assert from 'node:assert/strict';
import {createEmptyCase,createMedication,createEvent,createAssessment,createClinicalModule} from '../src/domain/models.js';
import {markLinkedAssessmentsNeedsReview,markLinkedClinicalModulesNeedsReview} from '../src/domain/assessment-state.js';
import {validateCase} from '../src/domain/validation.js';
import {migrateLegacy} from '../src/services/migration.js';

test('Naranjo linked to concomitant drug is invalid',()=>{const d=createEmptyCase();d.patient={...d.patient,hn:'1',age:{value:'30',unit:'years'},sex:'male',visitDate:'2026-01-01'};const m=createMedication({genericName:'Drug A',dose:'1',route:'PO',frequency:'OD',startDateTime:'2026-01-01T08:00',role:'concomitant'}),e=createEvent({term:'Rash',onsetDateTime:'2026-01-02T08:00',severity:'mild',outcome:'Recovered',management:'Stop drug'});d.medications.push(m);d.events.push(e);d.assessments.push(createAssessment(m.id,e.id));assert.ok(validateCase(d).errors.includes('assessment_drug_not_suspected'))});
test('Source edit marks linked assessment needs review',()=>{const d=createEmptyCase(),m=createMedication({role:'suspected'}),e=createEvent();d.medications.push(m);d.events.push(e);d.assessments.push(createAssessment(m.id,e.id));markLinkedAssessmentsNeedsReview(d,{drugId:m.id});assert.equal(d.assessments[0].status,'needs_review')});
test('Timeline legacy import does not import ambiguous Naranjo',()=>{const input={patient:{patientHn:'H1',patientAge:'45',patientSex:'ชาย'},drugs:[{name:'A',dose:'1',start:'2026-01-01',suspected:true}],adrs:[{event:'Rash',date:'2026-01-02',severity:'Mild',action:'stop',outcome:'recovered'}]};const r=migrateLegacy(input);assert.equal(r.data.assessments.length,0);assert.ok(r.report.includes('legacy_naranjo_not_imported'));assert.equal(r.data.patient.sex,'male')});

test('Final print requires phenotype when pharmacist concludes allergic',()=>{const d=createEmptyCase();d.patient={...d.patient,hn:'H1',age:{value:'20',unit:'years'},sex:'female',visitDate:'2026-01-01'};const m=createMedication({genericName:'Drug A',dose:'1 tab',route:'PO',frequency:'OD',startDateTime:'2026-01-01T08:00',role:'suspected'}),e=createEvent({term:'Rash',onsetDateTime:'2026-01-02T08:00',severity:'mild',outcome:'Recovered',management:'Stopped'});d.medications.push(m);d.events.push(e);const a=createAssessment(m.id,e.id);for(const q of Object.keys(a.answers)){a.answers[q]={answer:'no',rationale:'documented'}};a.status='complete';a.completed=true;a.score=0;a.classification='doubtful';d.assessments.push(a);d.conclusions=[{drugId:m.id,eventId:e.id,conclusion:'probable',relationshipType:'allergic',reasoning:'compatible history',recommendations:[]}];assert.ok(validateCase(d,{forPrint:true}).errors.includes('allergic_phenotype_required'))});


test('Source edit marks linked optional clinical module needs review without blocking core validation',()=>{const d=createEmptyCase(),m=createMedication({role:'suspected'}),e=createEvent();d.medications.push(m);d.events.push(e);d.clinicalModules.push(createClinicalModule('alden',{drugId:m.id,eventId:e.id,result:{score:3,category:'possible'}}));markLinkedClinicalModulesNeedsReview(d,{eventId:e.id});assert.equal(d.clinicalModules[0].status,'needs_review');const v=validateCase(d);assert.ok(v.warnings.includes('clinical_module_needs_review'))});

test('Other phenotype needs detail when final relationship is allergic',()=>{const d=createEmptyCase();d.patient={...d.patient,hn:'H2',age:{value:'12',unit:'years'},sex:'male',visitDate:'2026-01-01'};const m=createMedication({genericName:'Drug B',dose:'1',route:'PO',frequency:'OD',startDateTime:'2026-01-01T08:00',role:'suspected'}),e=createEvent({term:'Reaction',onsetDateTime:'2026-01-02T08:00',phenotype:'other',phenotypeOther:'',severity:'mild',outcome:'Recovered',management:'Stopped'});d.medications.push(m);d.events.push(e);const a=createAssessment(m.id,e.id);for(const q of Object.keys(a.answers)){a.answers[q]={answer:'no',rationale:'documented'}};const complete={...a,status:'complete',completed:true,score:0,classification:'doubtful',rationaleErrors:[]};d.assessments.push(complete);d.conclusions.push({drugId:m.id,eventId:e.id,conclusion:'possible',relationshipType:'allergic',reasoning:'clinical assessment',recommendations:[]});const v=validateCase(d,{forPrint:true});assert.ok(v.errors.includes('allergic_phenotype_detail_required'))});

test('broken optional clinical-module references are structural errors',()=>{const d=createEmptyCase();d.patient={...d.patient,hn:'H3',age:{value:'40',unit:'years'},sex:'male',visitDate:'2026-01-01'};d.clinicalModules.push(createClinicalModule('penfast',{drugId:'missing-drug',inputs:{},result:null}));const v=validateCase(d);assert.ok(v.errors.includes('clinical_module_reference_invalid'))});

test('duplicate pharmacist conclusions for the same Drug × ADR pair are rejected',()=>{const d=createEmptyCase(),m=createMedication({genericName:'Drug',dose:'1',route:'PO',frequency:'OD',startDateTime:'2026-01-01T08:00',role:'suspected'}),e=createEvent({term:'Rash',onsetDateTime:'2026-01-02T08:00',severity:'mild',outcome:'Recovered',management:'Stopped'});d.medications.push(m);d.events.push(e);d.conclusions=[{id:'c1',drugId:m.id,eventId:e.id},{id:'c2',drugId:m.id,eventId:e.id}];const v=validateCase(d);assert.ok(v.errors.includes('conclusion_duplicate_pair'))});
