import {getLang} from './i18n.js';

export const seriousnessLabels={death:{th:'เสียชีวิต',en:'Death'},life_threatening:{th:'อันตรายถึงชีวิต',en:'Life-threatening'},hospitalization:{th:'เข้ารักษาใน รพ.',en:'Initial hospitalization'},prolonged_hospitalization:{th:'นอน รพ. นานขึ้น',en:'Prolonged hospitalization'},disability:{th:'พิการ/สูญเสียความสามารถสำคัญ',en:'Disability/incapacity'},congenital_anomaly:{th:'ความผิดปกติแต่กำเนิด',en:'Congenital anomaly'},important_medical_event:{th:'เหตุการณ์สำคัญทางการแพทย์',en:'Important medical event'}};
export const phenotypeLabels={urticaria:{th:'ลมพิษ (Urticaria)',en:'Urticaria'},angioedema:{th:'Angioedema',en:'Angioedema'},anaphylaxis:{th:'Anaphylaxis',en:'Anaphylaxis'},bronchospasm:{th:'หลอดลมหดเกร็ง (Bronchospasm)',en:'Bronchospasm'},morbilliform:{th:'ผื่น Maculopapular/Morbilliform',en:'Maculopapular/Morbilliform eruption'},fde:{th:'Fixed Drug Eruption (FDE)',en:'Fixed Drug Eruption'},agep:{th:'AGEP',en:'AGEP'},dress:{th:'DRESS',en:'DRESS'},sjs:{th:'SJS',en:'SJS'},ten:{th:'TEN',en:'TEN'},dili:{th:'DILI / Hepatitis',en:'DILI/Hepatitis'},ain:{th:'Interstitial nephritis',en:'Interstitial nephritis'},vasculitis:{th:'Vasculitis',en:'Vasculitis'},cytopenia:{th:'Cytopenia',en:'Cytopenia'},serum_sickness:{th:'Serum sickness-like reaction',en:'Serum sickness-like reaction'},other:{th:'อื่น ๆ',en:'Other'}};
export const enumLabels={
 sex:{male:{th:'ชาย',en:'Male'},female:{th:'หญิง',en:'Female'}},
 ageUnit:{years:{th:'ปี',en:'years'},months:{th:'เดือน',en:'months'},days:{th:'วัน',en:'days'}},
 severity:{mild:{th:'เล็กน้อย (Mild)',en:'Mild'},moderate:{th:'ปานกลาง (Moderate)',en:'Moderate'},severe:{th:'รุนแรง (Severe)',en:'Severe'}},
 timing:{immediate:{th:'ทันที (Immediate)',en:'Immediate'},delayed:{th:'ล่าช้า (Delayed)',en:'Delayed'},indeterminate:{th:'ระบุไม่ได้',en:'Indeterminate'}},
 mechanism:{unknown:{th:'ไม่ทราบ',en:'Unknown'},suspected_ige:{th:'สงสัย IgE-mediated',en:'Suspected IgE-mediated'},non_ige_immediate:{th:'Non-IgE immediate',en:'Non-IgE immediate'},t_cell:{th:'สงสัย T-cell mediated',en:'Suspected T-cell mediated'},other:{th:'อื่น ๆ',en:'Other'}},
 naranjo:{definite:{th:'ชัดเจน (Definite)',en:'Definite'},probable:{th:'น่าจะใช่ (Probable)',en:'Probable'},possible:{th:'เป็นไปได้ (Possible)',en:'Possible'},doubtful:{th:'ไม่น่าใช่ (Doubtful)',en:'Doubtful'}},
 conclusion:{confirmed:{th:'ยืนยันแล้ว (Confirmed)',en:'Confirmed'},highly_probable:{th:'มีความเป็นไปได้สูงมาก',en:'Highly probable'},probable:{th:'น่าจะเป็น',en:'Probable'},possible:{th:'เป็นไปได้',en:'Possible'},unlikely:{th:'ไม่น่าเป็น',en:'Unlikely'},unable_to_assess:{th:'ประเมินไม่ได้',en:'Unable to assess'}},
 relationship:{allergic:{th:'Drug allergy / hypersensitivity',en:'Allergic / hypersensitivity'},non_allergic_adr:{th:'ADR ที่ไม่ใช่การแพ้ยา',en:'Non-allergic ADR'},indeterminate:{th:'ยังระบุไม่ได้',en:'Indeterminate'}},
 recommendation:{avoid_culprit:{th:'หลีกเลี่ยงยาต้นเหตุ',en:'Avoid culprit drug'},avoid_related_class:{th:'หลีกเลี่ยงยาที่เกี่ยวข้อง/กลุ่มยา',en:'Avoid related drug/class'},alternative_allowed:{th:'สามารถใช้ยาทางเลือกได้',en:'Alternative drug allowed'},refer_allergy_specialist:{th:'ส่งต่อผู้เชี่ยวชาญด้านแพ้ยา',en:'Refer to allergy specialist'},further_testing:{th:'พิจารณาตรวจเพิ่มเติมด้านแพ้ยา',en:'Further allergy testing recommended'},no_avoidance_required:{th:'ไม่จำเป็นต้องหลีกเลี่ยงยาในอนาคต',en:'No future avoidance required'},other:{th:'อื่น ๆ',en:'Other'}}
};
const moduleCategories={penfast:{incomplete:{th:'ข้อมูลไม่ครบ',en:'Incomplete'},very_low:{th:'เสี่ยงต่ำมาก',en:'Very low risk'},low:{th:'เสี่ยงต่ำ',en:'Low risk'},moderate:{th:'เสี่ยงปานกลาง',en:'Moderate risk'},high:{th:'เสี่ยงสูง',en:'High risk'}},regiscar:{incomplete:{th:'ข้อมูลไม่ครบ',en:'Incomplete'},no_case:{th:'ไม่เข้าเกณฑ์',en:'No case'},possible:{th:'Possible',en:'Possible'},probable:{th:'Probable',en:'Probable'},definite:{th:'Definite',en:'Definite'}},alden:{incomplete:{th:'ข้อมูลไม่ครบ',en:'Incomplete'},very_unlikely:{th:'Very unlikely',en:'Very unlikely'},unlikely:{th:'Unlikely',en:'Unlikely'},possible:{th:'Possible',en:'Possible'},probable:{th:'Probable',en:'Probable'},very_probable:{th:'Very probable',en:'Very probable'}},schumock:{incomplete:{th:'ข้อมูลไม่ครบ',en:'Incomplete'},preventable:{th:'ป้องกันได้ (Preventable)',en:'Preventable'},not_preventable:{th:'ป้องกันไม่ได้ตามเกณฑ์',en:'Not preventable'},unable_to_determine:{th:'ข้อมูลไม่พอประเมิน',en:'Unable to determine'}}};
export function enumText(group,key,l=getLang()){return enumLabels[group]?.[key]?.[l]??String(key??'').replaceAll('_',' ')}
export function phenotypeText(e,l=getLang()){if(!e)return'-';if(e.phenotype==='other')return e.phenotypeOther?.trim()||phenotypeLabels.other[l];return phenotypeLabels[e.phenotype]?.[l]||e.phenotypeOther||'-'}
export function mechanismText(e,l=getLang()){if(!e)return'-';if(e.mechanism==='other')return e.mechanismOther?.trim()||enumText('mechanism','other',l);return enumText('mechanism',e.mechanism,l)}
export function seriousnessText(e,l=getLang()){return e?.seriousness?.length?e.seriousness.map(x=>seriousnessLabels[x]?.[l]||x).join(', '):(l==='th'?'ไม่เข้าเกณฑ์ Serious':'Not serious')}
export function recommendationsText(c,l=getLang()){return(c?.recommendations??[]).map(x=>enumText('recommendation',x,l)).join(', ')||(l==='th'?'ไม่มี':'None')}
export function moduleCategoryText(type,category,l=getLang()){return moduleCategories[type]?.[category]?.[l]??String(category??'').replaceAll('_',' ')}
export function moduleName(type){return({penfast:'PEN-FAST',regiscar:'RegiSCAR',alden:'ALDEN',schumock:'Schumock & Thornton'})[type]||type}
